# Site settings
title: David Rueter
email: info@davidrueter.com
description: > # this means to ignore newlines until "baseurl:"
 David is an artist and programmer based in Chicago, IL.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: davruet
github_username:  davruet
show_project_titles: false

# Build settings
markdown: kramdown
collections:
 projects:
  output: true
 texts:
  output: true