# Site settings
title: David Rueter
email: info@davidrueter.com
description: > # this means to ignore newlines until "baseurl:"
 David Rueter is a contemporary artist, with recent notable exhibitions including the 34th São Paulo Bienal and the 16th Venice Architecture Biennial.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: davruet
github_username:  davruet
show_project_titles: false

# Build settings
markdown: kramdown
collections:
 projects:
  output: true
 texts:
  output: true
